name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: npm i -g pnpm && pnpm install

    - name: Build project
      run: npm run b

    - name: Create tar.gz
      run: tar -czf public.tar.gz public/
      
    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "public.tar.gz"
        target: "/home/execapp/dev/electerm-web-demo"

    - name: Extract and replace on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/execapp/dev/electerm-web-demo
          cp -r public public-bak-`date +%Y%m%d%H%M%S`
          rm -rf public
          tar -xzf public.tar.gz
          rm public.tar.gz